###  Numpy array

In [1]:
import numpy as np

In [14]:
### Data types of numpy array is same throughout the array

In [8]:
import numpy as np
a1= np.array([2,4,5,4.3,3])
print(a1)
print(a1.dtype)


[2.  4.  5.  4.3 3. ]
float64


In [10]:
a2 = np.array(["harry",34,5.3,5])
print(a2)
print(a2.dtype)

['harry' '34' '5.3' '5']
<U32


In [17]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

print('a',a)
print('b',b)

m1 = ( a * b )
print(m1)

a [1. 2. 3.]
b [2. 2. 2.]
[2. 4. 6.]


In [35]:
a = np.array([1,2,3,4,5,6])
b = np.array(2) #--> all element of a is multiplyed by 2``


print('a',a)
print('b',b)

m1 = ( a * b )
print('a*b = ', m1)

a [1 2 3 4 5 6]
b 2
a*b =  [ 2  4  6  8 10 12]


### Broadcasting rules 
A) they are equel , or     
B) one of them is 1
    

In [36]:
a = np.array([[1,3,5],[2,4,6]])
b = np.array(5) # --> all element of a is multiple by b


print("a = ", a, 'dim',a.ndim)
print("b = ", b, 'dim',b.ndim)

print("a*b ")
print(a*b)

a =  [[1 3 5]
 [2 4 6]] dim 2
b =  5 dim 0
a*b 
[[ 5 15 25]
 [10 20 30]]


In [31]:
a = np.array ([[1,3,4],[5,6,7]])
b = np.array([-1,2,3])

print('a' , a , 'dim', a.ndim)
print('b' , b , 'dim', b.ndim)

print('a*b', a*b)

a [[1 3 4]
 [5 6 7]] dim 2
b [-1  2  3] dim 1
a*b [[-1  6 12]
 [-5 12 21]]


In [34]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,-3,4],[4,-5,6]])  #[1,2,3] is multiple by [2,-3,4] and a [4,5,6] is multiple by [4,-5,6]....

print("a", a , "shape", a.shape ,"dim", a.ndim)
print("b", b , "shape", b.shape ,"dim", b.ndim)

print("a*b", a*b)

a [[1 2 3]
 [4 5 6]] shape (2, 3) dim 2
b [[ 2 -3  4]
 [ 4 -5  6]] shape (2, 3) dim 2
a*b [[  2  -6  12]
 [ 16 -25  36]]


### np.linspace()

In [43]:
s1 = np.linspace(2,10,5) #start = 2, end = 10, part  = 5
print(s1)

[ 2.  4.  6.  8. 10.]


In [44]:
s2 = np.linspace(2,10,8)
print(s2)

[ 2.          3.14285714  4.28571429  5.42857143  6.57142857  7.71428571
  8.85714286 10.        ]


In [42]:
s3 = np.linspace(2,20,8,dtype = "int")
print(s3)

[ 2  4  7  9 12 14 17 20]


In [45]:
z1 = np.linspace(2,20)  #start = 2, end = 20 , num = 50 -->i.. think is defult )
print(z1)
print(z1.dtype)
print(len(z1))

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]
float64
50


In [50]:
j1 = np.linspace(2,20,7, retstep = True)
print(j1)

(array([ 2.,  5.,  8., 11., 14., 17., 20.]), 3.0)


### Copy() and View()

In [53]:
a = np.array([5,6,7,8,9,0])
print(a)

b = a.copy()
print(b)

a[0] = 50
print(a)
print(b)

[5 6 7 8 9 0]
[5 6 7 8 9 0]
[50  6  7  8  9  0]
[5 6 7 8 9 0]


In [54]:
c = np.array([1,2,3,4,5])
print(c)

d = c.view()

print(d)

c[0] = 6
print(c,d)

[1 2 3 4 5]
[1 2 3 4 5]
[6 2 3 4 5] [6 2 3 4 5]


###  Numpy random number

###  (01) np.random.random

In [56]:
a = np.random.random(5)
print(a)

[0.36433782 0.24410027 0.06282923 0.0344199  0.47726659]


In [67]:
import numpy as np
b1 = np.random.random((3,4))

print(b1)

[[0.6100578  0.66469411 0.21466245 0.55557727]
 [0.59732541 0.82354404 0.63445611 0.5069408 ]
 [0.66610444 0.20852077 0.73371867 0.31288131]]


###  (02)np.random.randint ( low, high, size )

In [72]:
a = np.random.randint(2,20,3)
print(a)

[ 7 17 10]


In [78]:
a2 = np.random.randint(10,50,(2,8))
print(a2)

## what i m trying to ::?
## return a np array of shape (3,4) with random element which a range to 10 to 50

[[25 13 44 14 38 25 25 38]
 [27 41 34 28 29 20 17 14]]


### (03) np.random.rand
it is similier of the np.random.randint..

it is a generate a value between a 0 to 1 in the given shape

In [80]:
 a = np.random.rand(3)
print(a)

[0.10915224 0.26346816 0.05184473]


In [81]:
b = np.random.rand(3,4)
print(b)

[[0.76930596 0.69525813 0.96433949 0.78980162]
 [0.24857056 0.02296372 0.28829918 0.02241595]
 [0.28195343 0.07326943 0.45262958 0.94294363]]


###  (04) np.random.choice

In [89]:
a = np.random.choice([1,2,3,4,5,6],size = 4)
print(a)

[1 5 5 4]


In [94]:
a = np.arange(2,100)
print(a)
b = np.random.choice(a,size = 5)
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[10 46 71 48 75]
