In [1]:
import numpy as np

# EXAMPLE : 1 
# Crwating a np.array using a liss

n1 = np.array([5,7,8,3,17])
print(n1)
print(type(n1))

[ 5  7  8  3 17]
<class 'numpy.ndarray'>


In [86]:
# Creating a numpy arrays using list and tuples

n1 = [10,20,30,40]
n2 = (10,2,0,5)

w1 = np.array(n1)
w2 = np.array(n2)

print(w1)
print(type(w1))
print(w2)
print(type(w2))

[10 20 30 40]
<class 'numpy.ndarray'>
[10  2  0  5]
<class 'numpy.ndarray'>


###  there are four properties of numpy arrays

In [87]:
s0 =np.array(7)
print(s0)
print(s0.dtype) # datatype  = int 32
print(s0.size) # size = no.of element = 1
print(s0.shape) # shape = ()
print(s0.ndim) # ndim =0

7
int32
1
()
0


In [88]:
s0 =np.array([7])
print(s0)
print(s0.dtype) # datatype  = int 32
print(s0.size) # size = no.of element = 1
print(s0.shape) # shape = ()
print(s0.ndim) # ndim =0

[7]
int32
1
(1,)
1


In [89]:
s0 =np.array([7,4,7,2,4,7,2,48])
print(s0)
print(s0.dtype) # datatype  = int 32
print(s0.size) # size = no.of element = 8
print(s0.shape) # shape = ()
print(s0.ndim) # ndim =0

[ 7  4  7  2  4  7  2 48]
int32
8
(8,)
1


In [15]:
parikshit = [[12,43,54,32],[32,45,34,65]]
print(parikshit)
print(type(parikshit))

[[12, 43, 54, 32], [32, 45, 34, 65]]
<class 'list'>


In [16]:
a1 = np.array(parikshit)
print(a1)
print(a1.dtype) #datatype = int32
print(a1.size) #size = 8
print(a1.shape) #shape = 2 raw and 3 coloume
print(a1.ndim) # only 2 entitys

[[12 43 54 32]
 [32 45 34 65]]
int32
8
(2, 4)
2


In [21]:
a2 = np.array([[[34,65,23,87],[65,87,96,90]],[[64,67,23,34],[87,23,67,23]]])
print(a2)
print(a2.dtype) #datatype = int32
print(a2.size) #size = 16
print(a2.shape) #shape = (2,2,4) (3rd dimetional, raws ,coloums)
print(a2.ndim) #  shape me hame 3 dimational mil rahe he so n-dimational could be = 3"

[[[34 65 23 87]
  [65 87 96 90]]

 [[64 67 23 34]
  [87 23 67 23]]]
int32
16
(2, 2, 4)
3



### (2).np.arrange ()

In [92]:
w1 = np.arange(10,20)# start = 10 , end = 20
print(w1)
print(w1.dtype)
print(w1.size)
print(w1.shape)
print(w1.ndim)

[10 11 12 13 14 15 16 17 18 19]
int32
10
(10,)
1


In [35]:
w2 = np.arange(5,25,4) #start = 5 , end = 25, step = 4
print(w2)
w3 = np.arange(30,10,-5) #start = 30, end = 10 , step = -5
print(w3)

[ 5  9 13 17 21]
[30 25 20 15]


### (3).np.zeros() generates array of zero 

In [41]:
d1 = np.zeros ((3,4))  # 3 = raws , 4 = coloum

print(d1)
# print(type(d1))
print(d1.dtype)
print(d1.size)
print(d1.shape)
print(d1.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
12
(3, 4)
2


In [43]:
d2 = np.zeros([4,2], dtype= 'int')
print(d2)
print(d2.dtype)
print(d2.size)
print(d2.shape)
print(d2.ndim)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
int32
8
(4, 2)
2


In [47]:
d3 = np.zeros((7),dtype='int')
print(d3)
print(d3.dtype)
print(d3.size)
print(d3.shape)
print(d3.ndim)

[0 0 0 0 0 0 0]
int32
7
(7,)
1


###  (04).np.ones()

In [49]:
n1 = np.ones((4,3), dtype = 'int') #rows = 4 , coloum = 3
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
n2 = np.ones((5,6))
print(n2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


###  Reshape() and shape properly
Array can be reshaped into its product of its factors

In [58]:
b1 = np.array([3,4,5,6,7,8,9,10,11,12,13,14])
print(b1)
print(b1.dtype)
print(b1.size)
print(b1.shape)
print(b1.ndim)

# factors of 12 = 1,2,3,4,6,12 --> factor means ketala sathe bhagi sakay....
#  to have aa 1 dimational array ne 2 dimational array ma fervava mate aene kai kai rite dimational kari sakay teni pair...
# pairs  = (3,4), (4,3) , (2,6) , (6,2) , (1,12) , (12,1)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
int32
12
(12,)
1


###  the array change when is reshape on the time of creation array ...the array was actuall change....
array create karti vakhte array ma reshape aapiye to array ae reshape na change ma aavi jay che ...

In [65]:
b2 = np.array ([3,4,5,6,7,8,9,10,11,12,13,14]).reshape(3,4) # raws = 2 and coloum =4

print(b2)
print(b2.shape)
print(b2.ndim)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
(3, 4)
2


In [68]:
print(b2.reshape(6,2))

[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [67]:
print(b2.shape)

(3, 4)


In [76]:
b4 = np.arange(1,19).reshape(2,9) # rows = 2, cols =9
print(b4)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [75]:
b4.reshape(2,3,3)
  # 2 = 2 parts (3rd dimational) , no of rows = 3, cols = 3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
h1 = b4.reshape(9,2)
print(h1)
print(h1.shape, h1.ndim)
print(b4.shape, b4.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]
(9, 2) 2
(2, 9) 2


### Reshape an  array after that creation ...how can be that done???

In [82]:
b4.shape = (3,2,3) # (3rd dimational(means 3 group ), 2 rows, 3 cols)
print(b4)
print(b4.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)


In [85]:
g1 = np.arange(2,14).reshape(3,4,1)
print(g1)
print(g1.shape)

[[[ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]]]
(3, 4, 1)
